# Generated by Django 3.1.4 on 2020-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(default='', max_length=50)),
                ('event_category', models.CharField(choices=[('IBSF', 'IBSF'), ('ACBS', 'ACBS'), ('National', 'NATIONAL'), ('Invitation', 'INVITATION'), ('Open Entry', 'OPEN ENTRY'), ('Professional', 'PROFESSIONAL')], default='', max_length=50)),
                ('sports_category', models.CharField(choices=[('Billiards', 'BILLIARDS'), ('Snooker', 'SNOOKER'), ('6REDS', '6REDS'), ('10REDS', '10REDS'), ('Pool', 'POOL'), ('Carrom', 'CARROM')], default='', max_length=50)),
                ('currency', models.CharField(choices=[('₹', '₹'), ('€', '€'), ('$', '$'), ('£', '£')], default='', max_length=50)),
                ('entry_fee', models.IntegerField(default=0)),
                ('prize_money_total', models.IntegerField(default=0)),
                ('prize_money_winner', models.IntegerField(default=0)),
                ('prize_money_runner_up', models.IntegerField(blank=True, default=0)),
                ('prize_money_semi_finalist', models.IntegerField(blank=True, default=0)),
                ('prize_money_quarter_finalist', models.IntegerField(blank=True, default=0)),
                ('prize_money_last16', models.IntegerField(blank=True, default=0)),
                ('prize_money_last32', models.IntegerField(blank=True, default=0)),
                ('prize_money_highestbreak_1', models.IntegerField(blank=True, default=0)),
                ('prize_money_highestbreak_2', models.IntegerField(blank=True, default=0)),
                ('prize_money_highestbreak_3', models.IntegerField(blank=True, default=0)),
                ('tournament_image1', models.ImageField(upload_to='tournament/images')),
                ('tournament_image2', models.ImageField(blank=True, upload_to='tournament/images')),
                ('tournament_venue', models.TextField()),
                ('tournament_city', models.CharField(default='', max_length=70)),
                ('tournament_startdate', models.DateTimeField(null=True)),
                ('tournament_enddate', models.DateTimeField(null=True)),
                ('tournament_year', models.CharField(default='', max_length=10)),
                ('tournament_desc', models.TextField()),
                ('bank_name', models.CharField(default='', max_length=500)),
                ('last_date_of_entry', models.DateTimeField(null=True)),
                ('account_number', models.PositiveBigIntegerField(default=0)),
                ('ifsc_code', models.CharField(blank=True, max_length=100)),
                ('paytm_number', models.CharField(default='', max_length=15)),
                ('name1', models.CharField(default='', max_length=100)),
                ('name2', models.CharField(blank=True, default='', max_length=100)),
                ('name3', models.CharField(blank=True, default='', max_length=100)),
                ('name4', models.CharField(blank=True, default='', max_length=100)),
                ('contact_num1', models.CharField(default='', max_length=15)),
                ('contact_num2', models.CharField(blank=True, default='', max_length=15)),
                ('contact_num3', models.CharField(blank=True, default='', max_length=15)),
                ('contact_num4', models.CharField(blank=True, default='', max_length=15)),
                ('details', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
            ],
        ),
    ]
