# Generated by Django 3.1.4 on 2021-01-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_desc',
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_file',
            field=models.FileField(blank=True, upload_to='tournament/files'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='draw_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_file',
            field=models.FileField(blank=True, upload_to='tournament/files'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_image3',
            field=models.ImageField(blank=True, upload_to='tournament/images'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_state',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='contact_num1',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='currency',
            field=models.CharField(blank=True, choices=[('₹', '₹'), ('€', '€'), ('$', '$'), ('£', '£')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='paytm_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_winner',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
