# Generated by Django 3.1.4 on 2021-01-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
