# Generated by Django 3.1.4 on 2021-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_show_on_concluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('AUD', 'AUD')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='last_date_of_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
