# Generated by Django 3.1.4 on 2021-01-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20210110_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='note1',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='tournament',
            name='note2',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
