# Generated by Django 3.1.4 on 2021-01-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20210111_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='event_category',
            field=models.CharField(choices=[('IBSF', 'IBSF'), ('ACBS', 'ACBS'), ('National', 'NATIONAL'), ('Invitation', 'INVITATION'), ('OpenEntry', 'OPEN ENTRY'), ('Professional', 'PROFESSIONAL')], default='', max_length=50),
        ),
    ]
