# Generated by Django 3.1.4 on 2021-01-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20210112_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='FINAL',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_Stage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last16_Stage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last32_Stage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last64_Stage',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prelim_Knockout',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='quarter_Finals',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tournament',
            name='semi_Finals',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
