# Generated by Django 3.1.4 on 2021-01-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_tournament_payement_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='payement_note',
            new_name='payment_note',
        ),
    ]
