# Generated by Django 3.1.4 on 2021-03-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20210214_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
