# Generated by Django 3.1.4 on 2021-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_tournament_payment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Fee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_no', models.CharField(default='', max_length=15)),
                ('event_name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('entry_fee', models.IntegerField(default=0)),
                ('payment_status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
