# Generated by Django 3.1.4 on 2021-04-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='collecting_fee',
            field=models.BooleanField(default=False),
        ),
    ]
