# Generated by Django 3.1.4 on 2021-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_auto_20210404_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='entry_fee',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_highestbreak_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_highestbreak_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_highestbreak_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_last16',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_last32',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_quarter_finalist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_runner_up',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_semi_finalist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_total',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize_money_winner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
