# Generated by Django 3.1.4 on 2020-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MEN_RANKING', models.TextField()),
                ('WOMEN_RANKING', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content_billiards', models.TextField()),
                ('content_6RED', models.TextField()),
                ('content_10RED', models.TextField()),
                ('content_15RED', models.TextField()),
                ('content_pool', models.TextField()),
                ('content_carrom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Banner', models.ImageField(upload_to='home/images')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writing_About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('content_about', models.TextField()),
                ('content_billiards', models.TextField()),
                ('content_snooker', models.TextField()),
                ('content_pool', models.TextField()),
                ('content_carrom', models.TextField()),
            ],
        ),
    ]
