# Generated by Django 3.1.4 on 2020-12-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing_about',
            name='content_general_tips',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
