# Generated by Django 3.1.4 on 2020-12-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_writing_about_content_general_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='home/images')),
                ('sport_name', models.CharField(choices=[('Billiards', 'BILLIARDS'), ('Snooker', 'SNOOKER'), ('6REDS', '6REDS'), ('10REDS', '10REDS'), ('Pool', 'POOL'), ('Carrom', 'CARROM')], default='', max_length=100)),
            ],
        ),
    ]
