# Generated by Django 3.1.4 on 2021-01-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_champion_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='event',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='champion',
            name='sport_name',
            field=models.CharField(choices=[('Billiards', 'BILLIARDS'), ('Snooker', 'SNOOKER'), ('6REDS/10REDS', '6REDS/10REDS'), ('Carrom/Pool', 'CARROM/POOL')], default='', max_length=100),
        ),
    ]
