# Generated by Django 3.1.4 on 2021-01-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210103_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing_about',
            name='content_equipments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
