# Generated by Django 3.1.4 on 2021-01-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_writing_about_content_equipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing_about',
            name='content_about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writing_about',
            name='content_billiards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writing_about',
            name='content_carrom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writing_about',
            name='content_equipments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writing_about',
            name='content_general_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writing_about',
            name='content_pool',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writing_about',
            name='content_snooker',
            field=models.TextField(blank=True),
        ),
    ]
