# Generated by Django 3.1.4 on 2021-01-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210103_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('content_national', models.TextField(blank=True)),
                ('content_international', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('content_association', models.TextField(blank=True)),
                ('content_clubs', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sponser',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
