# Generated by Django 3.1.4 on 2021-01-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210104_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, default='', max_length=100)),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(upload_to='home/images')),
                ('content', models.TextField()),
            ],
        ),
    ]
