# Generated by Django 3.1.4 on 2021-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponser',
            name='file',
            field=models.FileField(blank=True, upload_to='home/files'),
        ),
    ]
