# Generated by Django 3.1.4 on 2021-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing_about',
            name='content_site_terms',
            field=models.TextField(blank=True),
        ),
    ]
