# Generated by Django 3.1.4 on 2021-01-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_writing_about_content_site_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='MEN_RANKING',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='WOMEN_RANKING',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content_10RED',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content_15RED',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content_6RED',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content_billiards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content_carrom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='content_pool',
            field=models.TextField(blank=True),
        ),
    ]
