# Generated by Django 3.1.4 on 2021-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210106_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='MEN_RANKING',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='WOMEN_RANKING',
        ),
        migrations.AddField(
            model_name='ranking',
            name='category',
            field=models.CharField(choices=[('Men-Ranking-Billiards', 'Men-Ranking-Billiards'), ('Men-Ranking-Snooker', 'Men-Ranking-Snooker'), ('Women-Ranking-Billiards', 'Women-Ranking-Billiards'), ('Women-Ranking-Snooker', 'Women-Ranking-Snooker')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ranking',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ranking',
            name='content_extra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ranking',
            name='image',
            field=models.ImageField(default='', upload_to='home/images'),
            preserve_default=False,
        ),
    ]
