# Generated by Django 3.1.4 on 2021-01-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210125_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='top_rank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
