# Generated by Django 3.1.4 on 2021-01-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_ranking_top_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='category',
            field=models.CharField(choices=[('Men Ranking Billiards', 'Men Ranking Billiards'), ('Men Ranking Snooker', 'Men Ranking Snooker'), ('Women Ranking Billiards', 'Women Ranking Billiards'), ('Women Ranking Snooker', 'Women Ranking Snooker')], default='', max_length=100),
        ),
    ]
