# Generated by Django 3.1.4 on 2021-02-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210215_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='home/images')),
                ('caption', models.CharField(blank=True, default='', max_length=50)),
                ('content_equipments', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='writing_about',
            name='content_equipments',
        ),
    ]
