# Generated by Django 3.1.4 on 2021-02-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210215_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='image',
            new_name='image_at_back',
        ),
        migrations.AddField(
            model_name='equipment',
            name='image_at_front',
            field=models.ImageField(default='', upload_to='home/images'),
            preserve_default=False,
        ),
    ]
