# Generated by Django 3.1.4 on 2021-02-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210215_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='content_10RED',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='content_15RED',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='content_6RED',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='content_billiards',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='content_carrom',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='content_pool',
        ),
        migrations.AddField(
            model_name='rule',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rule',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='image_at_back',
            field=models.ImageField(default='', upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='image_at_front',
            field=models.ImageField(default='', upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
