# Generated by Django 3.1.4 on 2021-02-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210216_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='content_international',
        ),
        migrations.RemoveField(
            model_name='title',
            name='content_national',
        ),
        migrations.AddField(
            model_name='title',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='title',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='title',
            name='image_at_back',
            field=models.ImageField(default='', upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='image_at_front',
            field=models.ImageField(default='', upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
