# Generated by Django 3.1.4 on 2021-03-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210216_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
