# Generated by Django 3.1.4 on 2021-03-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
