# Generated by Django 3.1.4 on 2021-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=100),
        ),
    ]
