# Generated by Django 3.1.4 on 2020-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('caption', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(choices=[('Men', 'MALE'), ('Women', 'FEMALE')], default='', max_length=50)),
                ('awards', models.TextField()),
                ('DOB', models.DateField()),
                ('image_at_back', models.ImageField(upload_to='profile/images')),
                ('image_at_front', models.ImageField(blank=True, upload_to='profile/images')),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('highest_break', models.TextField()),
                ('cue_in_use', models.CharField(default='', max_length=200)),
                ('club', models.CharField(default='', max_length=300)),
                ('represents', models.TextField(blank=True)),
                ('Employed_with', models.TextField(blank=True)),
                ('other_activites', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('Instagram_url', models.URLField(blank=True)),
                ('Facebook_url', models.URLField(blank=True)),
                ('Twitter_url', models.URLField(blank=True)),
            ],
        ),
    ]
