# Generated by Django 3.1.4 on 2020-12-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='champ_sport1',
            field=models.CharField(blank=True, choices=[('Men', 'MALE'), ('Women', 'FEMALE')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='champ_sport2',
            field=models.CharField(blank=True, choices=[('Men', 'MALE'), ('Women', 'FEMALE')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='champ_sport3',
            field=models.CharField(blank=True, choices=[('Men', 'MALE'), ('Women', 'FEMALE')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='champ_sport4',
            field=models.CharField(blank=True, choices=[('Men', 'MALE'), ('Women', 'FEMALE')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='champ_sport5',
            field=models.CharField(blank=True, choices=[('Men', 'MALE'), ('Women', 'FEMALE')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='champ_sport6',
            field=models.CharField(blank=True, choices=[('Men', 'MALE'), ('Women', 'FEMALE')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='is_champion',
            field=models.BooleanField(default=False),
        ),
    ]
