# Generated by Django 3.1.4 on 2021-01-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210101_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='champ_sport1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='champ_sport2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='champ_sport3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='champ_sport4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='champ_sport5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='champ_sport6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_champion',
        ),
    ]
