# Generated by Django 3.1.4 on 2021-01-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210101_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='highest_break',
        ),
        migrations.AddField(
            model_name='player',
            name='highest_break_billiards',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='highest_break_snooker',
            field=models.CharField(default='', max_length=100),
        ),
    ]
