# Generated by Django 3.1.4 on 2021-01-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210101_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='coache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=120)),
                ('DOB', models.DateField()),
                ('certificate', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('experience', models.CharField(blank=True, default='', max_length=100)),
                ('experties', models.TextField(blank=True)),
                ('formal_training', models.TextField(blank=True)),
                ('Employed_with', models.CharField(blank=True, default='', max_length=200)),
                ('other_activites', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='referee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=120)),
                ('DOB', models.DateField()),
                ('certificate', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('experience_in_national', models.CharField(blank=True, default='', max_length=100)),
                ('experience_in_international', models.CharField(blank=True, default='', max_length=100)),
                ('experties', models.TextField(blank=True)),
                ('formal_training', models.TextField(blank=True)),
                ('Employed_with', models.CharField(blank=True, default='', max_length=200)),
                ('other_activites', models.TextField(blank=True)),
            ],
        ),
    ]
