# Generated by Django 3.1.4 on 2021-01-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_coache_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coache',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referee',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
