# Generated by Django 3.1.4 on 2021-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210103_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='coache',
            name='image',
            field=models.ImageField(default='', upload_to='profile/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referee',
            name='image',
            field=models.ImageField(default='', upload_to='profile/images'),
            preserve_default=False,
        ),
    ]
