# Generated by Django 3.1.4 on 2021-01-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210103_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='formal_training',
        ),
        migrations.AddField(
            model_name='coache',
            name='caption_at_front',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='referee',
            name='caption_at_front',
            field=models.CharField(default='', max_length=50),
        ),
    ]
