# Generated by Django 3.1.4 on 2021-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20210215_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
