# Generated by Django 3.1.4 on 2021-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_player_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('association_name', models.CharField(blank=True, default='', max_length=100)),
                ('position_name', models.CharField(blank=True, default='', max_length=100)),
                ('position_fill', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(upload_to='profile/images')),
                ('content_association', models.TextField(blank=True)),
                ('position', models.ManyToManyField(blank=True, null=True, to='profiles.Position')),
            ],
        ),
    ]
