# Generated by Django 3.1.4 on 2021-03-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_association_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='content_association',
            new_name='content',
        ),
        migrations.AddField(
            model_name='association',
            name='image2',
            field=models.ImageField(blank=True, upload_to='profile/images'),
        ),
        migrations.AddField(
            model_name='association',
            name='pin_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
