# Generated by Django 3.1.4 on 2021-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210307_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
