# Generated by Django 3.1.4 on 2021-03-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_association_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='pin_code',
        ),
    ]
