# Generated by Django 3.1.4 on 2021-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='club',
            name='image3',
            field=models.ImageField(blank=True, upload_to='profile/images'),
        ),
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='image1',
            field=models.ImageField(blank=True, upload_to='profile/images'),
        ),
    ]
